image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - test
  - image

build:
  image: maven:3-jdk-8
  stage: build
  script: 
  - "mvn package -DskipTests"
  
test:
   image: maven:3-jdk-8
   stage: test
   script: 
   - "mvn -B test"

registry:
  stage: image
  script:
    - docker build -t registry.gitlab.com/tudonovo/core .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/tudonovo/core

